name: Prepare Preview
description: Comment the Preview URL Stage 1
inputs:
  COMMENT_ID:
    description: Comment ID
    required: true
  SHOPIFY_FLAG_STORE:
    description: Shopify store
    required: true
  PREVIEW_URL:
    description: Preview URL
    required: true
  EDITOR_URL:
    description: Editor URL
    required: true
  FAILED:
    description: Failed
    required: true

runs:
  using: composite
  steps:
    - name: Comment Link # Override the loading comment from the start with the actual values and links
      uses: peter-evans/create-or-update-comment@v2
      if: ${{ !inputs.FAILED }}
      with:
        comment-id: ${{ inputs.COMMENT_ID }}
        body: |
          | Store | Status | Preview | Editor | Date | Time |
          | :--- | :----- | :------ | :------ | :------ | :----- |
          | ${{ inputs.SHOPIFY_FLAG_STORE }} | ✅ Ready | <a href="${{ inputs.PREVIEW_URL }}" target="_blank">Preview</a> | [Editor](${{ inputs.EDITOR_URL }}) | ${{ steps.stats.outputs.date }} | ${{ steps.stats.outputs.time }}

          🛍️

          Store URL: https://${{ inputs.SHOPIFY_FLAG_STORE }}.myshopify.com
          Theme name: ${{ steps.stats.outputs.branch_name }}
          Preview URL: ${{ inputs.PREVIEW_URL }}
          Editor URL: ${{ inputs.EDITOR_URL }}

          *a DotDev preview*
        reactions: hooray
        edit-mode: replace

    - name: Output Step Failed # Create skeleton table and visualize failed state
      if: ${{ inputs.FAILED }}
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ inputs.COMMENT_ID }}
        body: |
          | Store | Status | Preview | Editor | Date | Time |
          | :--- | :----- | :------ | :------ | :------ | :----- |
          | ${{ inputs.SHOPIFY_FLAG_STORE }} | ❌ Failed |  |  | ${{ steps.stats.outputs.date }} | ${{ steps.stats.outputs.time }}

          🛍️

          Store URL: https://${{ inputs.SHOPIFY_FLAG_STORE }}.myshopify.com
          Theme name: ${{ steps.stats.outputs.branch_name }}

          ❌ 'Create Preview Link' failed ❌

          Please check if the following `inputs` are set correctly:
          - `SHOPIFY_CLI_THEME_TOKEN` [(?)](https://shopify.dev/themes/tools/theme-access)
          - `SHOPIFY_FLAG_STORE`

        edit-mode: replace
